# Numpy

In [2]:
import numpy as np

In [4]:
vector = np.array([0,1,2,3,4,5])
print(vector)

[0 1 2 3 4 5]


In [7]:
vector2 = np.array([1,2,3,4,5], dtype = np.float32)
print(vector2)

vector.dtype = np.float16 #malo TnT
print(vector)

vector3 = np.array([1,2,3,4,5])
vector3 = vector3.astype(np.float16) #El indicado... bueno °u°
print(vector3)

[1. 2. 3. 4. 5.]
[0.0e+00 0.0e+00 6.0e-08 0.0e+00 1.2e-07 0.0e+00 1.8e-07 0.0e+00 2.4e-07
 0.0e+00 3.0e-07 0.0e+00]
[1. 2. 3. 4. 5.]


In [8]:
print(vector3[3])

4.0


In [11]:
vector4 = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(vector4[0:8])

[0 1 2 3 4 5 6 7]


In [20]:
a=np.array([0,1,2])
b=np.array([0,-1,-3])
c=np.array([0,1,1])

print(a+b)
print(a-b)
print(a*b)
print(a/c)
print(2*a)
print(a>=1)
print(a**a)

[ 0  0 -1]
[0 2 5]
[ 0 -1 -6]
[nan  1.  2.]
[0 2 4]
[False  True  True]
[1 1 4]


C:\Users\kireli\AppData\Local\Temp\ipykernel_3760\2242344557.py:8: RuntimeWarning: invalid value encountered in divide
  print(a/c)


In [25]:
print(np.linspace(0,15,15))
print(np.arange(0,16,1))

[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Matriz

In [36]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.arange(0,16,1)
print(matrix)
print(matrix.shape)
print(a.shape)

nueva = matrix.reshape(9)
print(nueva)

print(matrix)

nuevo = a.reshape(4,4)
print(nuevo)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(16,)
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
mt1 = [[34,3],[67,7]]
mt2 = [[11,2],[78,3]]
mt3 = [[23,32],[90,1]]

arr1 = np.array([mt1,mt2,mt3])  


### filas columnas de cuando en cuanto se separan por comas y los intervalos con:
[fila_i:fiña_f , colum_i:colum_f , de cuanto en cuanto]

In [48]:
m =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m.shape)

print(m[:3,1:2]) #No olvidar que el segundo hay que sumarle1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[2]
 [5]
 [8]]


In [5]:
A = np.array([[2,-1],[1,3]])
B = np.array([3,5])

c = np.linalg.solve(A,B)
print(c)
print(A@c)


[2. 1.]
[3. 5.]
