In [4]:
import numpy as np

#### Ejercicio 1

In [6]:
A = np.array([[1,4],[-1,3],[2,-9]])
cero = np.zeros((3,2))

a = [A + cero, A-cero]

b = A-A

print(a)
print("-----------------------------------")
print(b)

[array([[ 1.,  4.],
       [-1.,  3.],
       [ 2., -9.]]), array([[ 1.,  4.],
       [-1.,  3.],
       [ 2., -9.]])]
-----------------------------------
[[0 0]
 [0 0]
 [0 0]]


#### Ejercicio 2

In [20]:
A = np.array([[3,0],[-1,5]])
B = np.array([[4,-2,1],[0,2,3]])

print(A)
print("---------------")
print(B)

[[ 3  0]
 [-1  5]]
---------------
[[ 4 -2  1]
 [ 0  2  3]]


In [38]:
#A+3B
B3 = 3 * B
print(B3)

[[12 -6  3]
 [ 0  6  9]]


In [41]:
#AB

r2 = A@B
print(r2)

[[12 -6  3]
 [-4 12 14]]


In [43]:
# A^3 Y B^2

r3 = A ** 3
r4 = B ** 2

print(r3,"\n---------------------\n",r4)

[[ 27   0]
 [ -1 125]] 
---------------------
 [[16  4  1]
 [ 0  4  9]]


In [44]:
#(5A)B

p1 = 5 * A
r5 = p1@B

print(r5)

[[ 60 -30  15]
 [-20  60  70]]


#### Ejercicio 3

In [49]:
rest = np.array([[30,15,4],[25,18,8]])
tienda = np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
T = tienda.T

costo = rest@T 

print("Tienda 1: ", (costo[0,0]+costo[1,0]))
print("Tienda 2: ", (costo[0,1]+costo[1,1]))

print("\nLa tienda mas accesible es la Tienda 1")

Tienda 1:  192.6
Tienda 2:  196.0

La tienda mas accesible es la Tienda 1


#### Ejercicio 4

In [51]:
Almc = np.array([[200,150,100],[75,100,125]])
Medio = np.array([[1.50,1.00,2.00],[1.75,1.50,1.00]])
M = Medio.T
print(M)

costo = Almc@M 

print("Camion: ", (costo[0,0]+costo[1,0]))
print("Tren: ", (costo[0,1]+costo[1,1]))

print("\nEl mejor transporte es el tren")

[[1.5  1.75]
 [1.   1.5 ]
 [2.   1.  ]]
Camion:  1112.5
Tren:  1081.25

El mejor transporte es el tren


#### Ejercicio 5

In [57]:
#A = np.array([[3 , 2], [6 , 4]]) es singular lo que hace que no se pueda resolver

# Calcular la pseudoinversa
ps = np.linalg.pinv(matriz)

print(ps)

A = np.array([[0.09230769 , 0.04615385], [0.06153846 , 0.03076923]])
B = np.array([6,9])

c = np.linalg.solve(A,B)
print(c)
print("-----comprobacion-----")
print(A@c)

[ 7.50000145e+08 -1.50000000e+09]
-----comprobacion-----
[6.         9.00000001]


In [58]:
A = np.array([[1,1],[1,-4]])
B = np.array([3,1])

c = np.linalg.solve(A,B)
print(c)
print("-----comprobacion-----")
print(A@c)


[2.6 0.4]
[3. 1.]


In [59]:
A = np.array([[2, 1, 2], [2, 3, -1],[1, 2, 2]])
B = np.array([3, 0, -12])

c = np.linalg.solve(A,B)
print(c)
print("-----comprobacion-----")
print(A@c)

[ 8.30769231 -6.69230769 -3.46153846]
-----comprobacion-----
[ 3.00000000e+00  1.77635684e-15 -1.20000000e+01]
